### ISSUE TITLE
[Not an issue] Will QtOpenGLTemplate have more features in the future?

### ISSUE THREAD

**Issue by shujaatak** [nemediano/QtOpenGLTemplate#1]
[QtOpenGLViewer](https://github.com/marcel-goldschen-ohm/QtOpenGLViewer) is a similar project written in old OpenGL API but having Mouse Rotation, Pan, Zoom, Object Selection and Hud Drawing features which greatly help in fast prototyping.

By the way, Thank you for this nice project!

**Comment by nemediano** [comment]
The only extra feature that I plan to add later is feature to load hierarchical meshes. So you can load a 3D models download from the internet and render it in a -more or less- easy way.
Yes, I am aware of QtOpenGLviewer I had use it extensively. There are two issues that come in my mind about it. 
First, since it was focused in fixed-pipeline, the support for modern OpenGL is limited. Basically one can only customize fragment shaders easily. If you want to use more in depth techniques like deferred shading is better to not use it.
Second, their aim is different. is for people that want to use graphics more than people that want to learn-experiment graphics. The graphics code is done for you in a generic way.
The aim for my template was to facilitate the learning an experiment of modern OpenGL (4.5 at the time of this writing). Think about people that want to follow https://learnopengl.com/ or http://www.opengl-tutorial.org/ and do not want to spent many time learning the pre-OpenGL tasks. And want to have enough control to use the template for advanced rendering techniques.
Thanks for the comment!
